version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - common-net
      
  authentication-service:
    image: authentication-service
    build: ./authentication-service
    restart: on-failure
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/users
      SPRING_DATASOURCE_USERNAME: user_admin
      SPRING_DATASOURCE_PASSWORD: user_admin01$
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/users",
        "spring.datasource.username" : "user_admin",
        "spring.datasource.password" : "user_admin01$",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "jwt.symmetric.key":"01234567890123456789012345678901"
      }'
    
    networks:
      - common-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user_admin01$
      MYSQL_DATABASE: users
      MYSQL_USER: user_admin
      MYSQL_PASSWORD: user_admin01$
      MYSQL_INITDB: /docker-entrypoint-initdb.d
    networks:
      - common-net
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    
  userservice:
    image: userservice
    build: ./userservice
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
    networks:
      - common-net
networks:
  common-net: